name: PR Test
on: 
 pull_request:
    types: [closed] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: alstol/Self-Reward-Actions@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       IMAGE_URL: https://media.tenor.com/images/9da8bb145d928fb9e53772588622ca53/tenor.gif
       MEME_HEADER: <NAME> just merged his own PR! lol!
